name: deploy to server
description: scp a directory from the build host to a destination server
inputs:
  ssh-private-key:
    description: private ssh key for destination server
    required: true
    default: "this is not a valid key"
  user:
    description: the user name on the destination server
    required: false
    default: root
  server:
    description: the destination server
    required: true
  alias:
    description: the alias for the server used in ssh and scp commands
    required: false
    default: "server"

outputs:
  key-file: # id of output
    description: the name of the ssh file created
runs:
  using: node12
  main: dist/index.js
  post: dist/clean.js
