name: install keys and deploy to server
description: 'Greet someone and record the time'
inputs:
  ssh-private-key:
    description: private ssh key for destination server
    required: true
    default: "this is not a valid key"
  ssh-key-name:
    description: the file name that is used to store the key (no folder)
    required: true
    default: "server.pk"
  server:
    description: the destination server
    required: true
    default: "www.example.com"

outputs:
  key-file: # id of output
    description: the name of the ssh file created
runs:
  using: node12
  main: dist/index.js
  post: dist/clean.js
