name: deployment test

on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: enable tmate console debugging     
        required: false
        default: "false"
  push:
    branches: [ main ]

defaults:
  run:
    shell: bash

jobs:
  deploy:
    name: upload client installers
    runs-on: ubuntu-latest
    steps:
      - name: install ssh key
        id: install-ssh
        uses: caberger/deploy@v1.0
        with:
          ssh-private-key:  ${{ secrets.FS_CLOUD_ABERGER }}
          ssh-key-name: fs
          server: fs.cloud.htl-leonding.ac.at
          source-folder: "~/deployment"
          destination-folder: "mist/deploy"
      - name: list result
        run: |
          ls -l ~
          cat ~/sshkeys/fs

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}

