name: deployment test

on:
  push:
    branches: [ master ]

defaults:
  run:
    shell: bash

jobs:
  deploy:
    name: upload client installers
    needs: [win, mac]
    runs-on: ubuntu-latest
    steps:
      - name: install ssh key
        id: install-ssh
        uses: caberger/deploy@v1.0
        with:
          ssh-private-key: "abs test"
          ssh-key-name: fs
          server: fs.cloud.htl-leonding.ac.at

