name: deployment test

on:
  workflow_dispatch:
    inputs:
      debug:
        description: enable tmate console debugging     
        required: false
        default: "disabled"
  push:
    branches: [ main ]

defaults:
  run:
    shell: bash

jobs:
  deploy:
    name: upload client installers
    runs-on: ubuntu-latest
    steps:
      - name: simulate a build of the project
        run: |
          mkdir -p ~/deployment
          echo "this is a test" > ~/deployment/test.txt

      - name: install ssh key
        id: install-ssh
        uses: caberger/deploy@v1.0
        with:
          ssh-private-key:  ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          user: ${{ secrets.SERVER_USER }}
          server: ${{ secrets.SERVER }}
          alias: server

      - name: Setup tmate session (for debugging only)
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug == 'enabled' }}

      - name: upload artififacts to the server
        run: |
          ssh server "ls -l"
          ssh server "rm -rf ~/deployment"
          scp -r ~/deployment/ server:~/
          ssh server "ls -l ~/deployment"


