name: deployment test

on:
  workflow_dispatch:
    inputs:
      debug:
        description: enable tmate console debugging     
        required: false
        default: "disabled"
  push:
    branches: [ main ]

defaults:
  run:
    shell: bash

jobs:
  deploy:
    name: upload client installers
    runs-on: ubuntu-latest
    steps:
      - name: prepare upload
        run: |
          mkdir -p ~/deployment
          echo "this is a test" > ~/deployment/test.txt

      - name: install ssh key
        id: install-ssh
        uses: caberger/deploy@v1.0
        with:
          ssh-private-key:  ${{ secrets.FS_CLOUD_ABERGER }}
          ssh-key-name: fs
          server: fs.cloud.htl-leonding.ac.at
          source: "~/deployment/*"
          destination-folder: "mist/deploy"
          user: ${{ secrets.SERVER_USER }}

      - name: display result
        run: |
          cat ~/deployment/test.txt

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug == 'enabled' }}

