name: demonstration of ssh and scp

on:
  workflow_dispatch:
    inputs:
      debug:
        description: enable tmate console debugging     
        required: false
        default: "disabled"
  push:
    branches: [ main ]

defaults:
  run:
    shell: bash

jobs:
  ubuntu:
    name: ssh and scp on ubuntu
    runs-on: ubuntu-latest
    steps:

      - name: install ssh key on ubuntu
        uses: caberger/install-ssh-key@v1.0
        with:
          ssh-private-key:  ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          user: ${{ secrets.SERVER_USER }}
          server: ${{ secrets.SERVER }}
          alias: server

      - name: simulate a build of the project
        run: |
          mkdir -p ~/deployment
          echo "this is a test from ubuntu runner" > ~/deployment/test.txt

      - name: keyscan
        run: ssh-keyscan -H -t rsa -v o.aberger.at || echo "keyscan failed"

      - name: Setup tmate session (for debugging only)
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug == 'enabled' }}

      - name: upload artifacts to the server
        run: |
          ssh server "rm -rf ~/deployment"
          scp -r ~/deployment/ server:~/
          ssh server "ls -l ~/deployment"
          ssh server "cat ~/deployment/test.txt"

  windows:
    name: ssh and scp on windows
    runs-on: windows-latest
    steps:
      - name: install ssh key on windows
        uses: caberger/install-ssh-key@v1.0
        with:
          ssh-private-key:  ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          user: ${{ secrets.SERVER_USER }}
          server: ${{ secrets.SERVER }}
          alias: server

      - name: upload artifacts
        run: |
          echo "this is a test for windows ssh" > test.txt
          scp test.txt server:
          ssh server pwd
          ssh server "ls -l"
          ssh server "cat test.txt"
  osx:
    name: ssh and scp on osx runner
    runs-on: macos-latest
    steps:
      - name: install ssh key on osx
        uses: caberger/install-ssh-key@v1.0
        with:
          ssh-private-key:  ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          user: ${{ secrets.SERVER_USER }}
          server: ${{ secrets.SERVER }}
          alias: server

      - name: upload artifacts
        run: |
          echo "this is a test for osx ssh" > test-mac.txt
          scp test-mac.txt server:
          ssh server "cat test-mac.txt"
