name: demonstration of ssh and scp

on:
  workflow_dispatch:
    inputs:
      debug:
        description: enable tmate console debugging     
        required: false
        default: "disabled"
  push:
    branches: [ main ]

defaults:
  run:
    shell: bash

jobs:
  ubuntu:
    name: ssh and scp on ubuntu
    runs-on: ubuntu-latest
    steps:

      - name: install ssh key on ubuntu
        id: install-ssh
        uses: caberger/install-ssh-key@v1.0
        with:
          ssh-private-key:  ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          user: ${{ secrets.SERVER_USER }}
          server: ${{ secrets.SERVER }}
          alias: server

      - name: Setup tmate session (for debugging only)
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug == 'enabled' }}

      - name: simulate a build of the project
        run: |
          mkdir -p ~/deployment
          echo "this is a test" > ~/deployment/test.txt

      - name: upload artififacts to the server
        run: |
          ssh server "rm -rf ~/deployment"
          scp -r ~/deployment/ server:~/
          ssh server "ls -l ~/deployment"
          ssh server "cat ~/deployment/test.txt"
  windows:
    name: ssh and scp on ubuntu
    runs-on: windows-latest

    steps:
      - name: install ssh key on windows
        id: install-ssh
        uses: caberger/install-ssh-key@v1.0
        with:
          ssh-private-key:  ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          user: ${{ secrets.SERVER_USER }}
          server: ${{ secrets.SERVER }}
          alias: server

      - name: upload artififacts to the server
        run: |
          echo "this is a test for windows ssh" > ~/test.txt
          scp ~/test.txt server:~/
          ssh server "type ~/test.txt"
